services:

  nginx:
    image: nginx
    build:
      context: requirements/nginx/.
      args:
        - CRED_PATH
        - CRED_CERT
        - CRED_KEY
        - COUNTRY
        - STATE
        - LOCALITY
        - ORGANIZATION
        - ORG_UNIT
        - COMMON_NAME
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - v_web:/var/www/html
  wordpress:
    image: wordpress
    build: requirements/wordpress/.
    container_name: wordpress
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - v_web:/var/www/html
    env_file:
      - .env
    secrets:
      - wp_admin_password
      - wp_guest_password
      - db_password
  mariadb:
    image: mariadb
    build: requirements/mariadb/.
    container_name: mariadb
    restart: on-failure
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - v_db:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
volumes:
  v_web:
    name: v_web
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/shrodrig/data/wordpress
  v_db:
    name: v_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/shrodrig/data/mariadb
networks:
  inception:
    name: inception
    driver: bridge
secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_guest_password:
    file: ../secrets/wp_guest_password.txt